# Generated by Django 4.0.6 on 2022-08-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor_code',
            name='LCActive',
            field=models.BooleanField(choices=[(0, 'Deactive'), (1, 'Active')], default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='labor_code',
            name='LCDefaultRates',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Default Rate'),
        ),
    ]
